# Generated by Django 6.0.5 on 2026-05-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vehicle_latitude_vehicle_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='price_per_day',
            field=models.IntegerField(null=True),
        ),
    ]
