# Generated by Django 6.0.5 on 2026-05-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vehicle_price_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='location_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
