# Generated by Django 6.0.5 on 2026-06-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='image',
            field=models.ImageField(upload_to='dashboards/'),
        ),
    ]
